apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/f3lin/sockshop-k8s.git
    targetRevision: dev
    path: app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true