# This YAML file contains custom values for the Argo CD Helm chart installation.
# It is located at /home/f3lin/workspace/projects/sockshop-k8s/addons/argocd-values.yaml.
# The Argo CD Helm chart can be found at: https://artifacthub.io/packages/helm/argo/argo-cd.
# To install Argo CD using this values file, use the following Helm command:
# helm repo add argo https://argoproj.github.io/argo-helm
# helm repo update
# helm install argo-cd argo/argo-cd -f argocd-values.yaml
global:
  domain: argocd.monlabo.de  

configs:
  params:
    server.insecure: true

server:             
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls: true