---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: front-end
  labels:
    name: front-end
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end
